[tool.black]
line-length = 100
target-version = ['py38']
skip-string-normalization = true
skip-magic-trailing-comma = true
skip = ['test_files']

[tool.isort]
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
ensure_newline_before_comments = true
use_parentheses = true
skip_gitignore = true
skip = ['test_files']
